#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const outPath = resolve(repoRoot, 'src/lc0/generated/tvmPackedF16Wgsl.ts');

const kernels = [
  ['ATTENTION_BLOCK_QKV_TVM_PACKED_F16_WGSL', 'src/lc0/kernels/tvm/attention_block_qkv_packed_f16.wgsl'],
  ['ATTENTION_OUTPUT_PROJ_TVM_PACKED_F16_WGSL', 'src/lc0/kernels/tvm/attention_output_proj_residual_packed_f16.wgsl'],
  ['FFN_DENSE1_TVM_PACKED_F16_WGSL', 'src/lc0/kernels/tvm/ffn_dense1_sqrrelu_packed_f16.wgsl'],
  ['FFN_DENSE2_TVM_PACKED_F16_WGSL', 'src/lc0/kernels/tvm/ffn_dense2_residual_packed_f16.wgsl'],
];

function asTemplateLiteral(source) {
  return '`' + source.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
}

function sha256(source) {
  return createHash('sha256').update(source).digest('hex');
}

function buildOutput() {
  const entries = kernels.map(([name, relativePath]) => {
    const source = readFileSync(resolve(repoRoot, relativePath), 'utf8');
    return { name, relativePath, source, sha256: sha256(source), bytes: Buffer.byteLength(source, 'utf8') };
  });
  let out = `// Generated by scripts/generate_lc0_tvm_wgsl_kernels.mjs. Do not edit by hand.\n`;
  out += `// Source WGSL files live under src/lc0/kernels/tvm/.\n\n`;
  out += `export const LC0_TVM_PACKED_F16_KERNELS = ${JSON.stringify(entries.map(({ name, relativePath, sha256, bytes }) => ({ name, sourcePath: relativePath, sha256, bytes })), null, 2)} as const;\n\n`;
  for (const entry of entries) {
    out += `// source: ${entry.relativePath}\n`;
    out += `// sha256: ${entry.sha256}\n`;
    out += `export const ${entry.name} = ${asTemplateLiteral(entry.source)};\n\n`;
  }
  return out;
}

const expected = buildOutput();
if (process.argv.includes('--check')) {
  const current = readFileSync(outPath, 'utf8');
  if (current !== expected) {
    console.error('Generated TVM packed-f16 WGSL module is stale. Run: npm run lc0:generate-tvm-wgsl');
    process.exit(1);
  }
} else {
  writeFileSync(outPath, expected);
}
