#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

const kernels = [
  ['ATTENTION_BLOCK_QKV_TVM_PACKED_F16_WGSL', 'src/lc0/kernels/tvm/attention_block_qkv_packed_f16.wgsl'],
  ['ATTENTION_OUTPUT_PROJ_TVM_PACKED_F16_WGSL', 'src/lc0/kernels/tvm/attention_output_proj_residual_packed_f16.wgsl'],
  ['FFN_DENSE1_TVM_PACKED_F16_WGSL', 'src/lc0/kernels/tvm/ffn_dense1_sqrrelu_packed_f16.wgsl'],
  ['FFN_DENSE2_TVM_PACKED_F16_WGSL', 'src/lc0/kernels/tvm/ffn_dense2_residual_packed_f16.wgsl'],
];

function asTemplateLiteral(source) {
  return '`' + source.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
}

let out = `// Generated by scripts/generate_lc0_tvm_wgsl_kernels.mjs. Do not edit by hand.\n`;
out += `// Source WGSL files live under src/lc0/kernels/tvm/.\n\n`;
for (const [name, relativePath] of kernels) {
  const source = readFileSync(resolve(repoRoot, relativePath), 'utf8');
  out += `export const ${name} = ${asTemplateLiteral(source)};\n\n`;
}
writeFileSync(resolve(repoRoot, 'src/lc0/generated/tvmPackedF16Wgsl.ts'), out);
