#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const repoRoot = resolve(import.meta.dirname, '..');
const sourcePath = process.argv[2]
  ? resolve(process.argv[2])
  : resolve(repoRoot, '../repos/lc0/src/neural/encoder.cc');
const outPath = process.argv[3]
  ? resolve(process.argv[3])
  : resolve(repoRoot, 'src/lc0/generatedPolicyMap.ts');

const source = readFileSync(sourcePath, 'utf8');
const match = source.match(/const char\* kMoveStrs\[\]\s*=\s*\{([\s\S]*?)\};/);
if (!match) throw new Error(`Could not find kMoveStrs[] in ${sourcePath}`);

const moves = [...match[1].matchAll(/"([a-h][1-8][a-h][1-8][qrb]?)"/g)].map((m) => m[1]);
if (moves.length !== 1858) throw new Error(`Expected 1858 LC0 policy moves, got ${moves.length}`);
if (new Set(moves).size !== moves.length) throw new Error('LC0 policy moves are not unique');

const content = `// Generated by scripts/generate_lc0_policy_map.mjs from ${sourcePath}\n` +
`// Do not edit by hand. Regenerate after updating the LC0 source checkout.\n\n` +
`export const LC0_POLICY_MAP = 'lc0_1858_from_encoder_cc' as const;\n` +
`export const LC0_POLICY_MOVES = ${JSON.stringify(moves, null, 2)} as const;\n` +
`export const LC0_POLICY_SIZE = LC0_POLICY_MOVES.length;\n`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, content);
console.log(`Wrote ${moves.length} LC0 policy moves to ${outPath}`);
