#!/usr/bin/env node
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';

const DEFAULT_OUT = 'artifacts/tvm/lc0_tvmjs_timing_breakdown_summary.json';
const STARTUP_KEYS = [
  'manifestFetchMs',
  'manifestJsonMs',
  'tvmjsBundleLoadMs',
  'requestAdapterMs',
  'requestDeviceMs',
  'wasmFetchVerifyMs',
  'tvmjsInstantiateMs',
  'tvmInitWebGpuMs',
  'tensorCacheFetchMs',
  'systemLibMs',
  'webgpuPipelinePrebuildMs',
  'createVirtualMachineMs',
  'inputTensorAllocMs',
  'inputUploadMs',
];
const EVAL_KEYS = [
  'tvmBatchEvalMs',
  'encodeMs',
  'inputConvertMs',
  'inputTensorAllocMs',
  'inputUploadMs',
  'setInputMs',
  'tvmInvokeMs',
  'outputHandleMs',
  'outputReadbackMs',
  'outputDecodeMs',
];
const POSITION_EVAL_KEYS = ['legalPriorsMs'];

function usage() {
  console.log(`Usage: node scripts/summarize_lc0_tvmjs_timing_breakdown.mjs --in PATH [--in PATH ...] [options]\n\nSummarizes observed TVMJS/WebGPU timing buckets from smoke or TVMJS-vs-hybrid matrix artifacts.\nResearch-only: this reports measured buckets and explicit caveats; it does not infer live GPU residency or promotion readiness.\n\nOptions:\n  --in PATH    Input JSON artifact; may be repeated or comma-separated\n  --out PATH   Output JSON summary (default ${DEFAULT_OUT})\n  --no-write   Print only\n  -h, --help   Show help\n`);
}

function parseArgs(argv) {
  const args = { inputs: [], out: DEFAULT_OUT, write: true };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = () => { if (i + 1 >= argv.length) throw new Error(`${arg} requires a value`); return argv[++i]; };
    if (arg === '--in') args.inputs.push(...next().split(',').map((item) => item.trim()).filter(Boolean));
    else if (arg === '--out') args.out = next();
    else if (arg === '--no-write') args.write = false;
    else if (arg === '-h' || arg === '--help') args.help = true;
    else throw new Error(`Unknown option: ${arg}`);
  }
  if (!args.help && !args.inputs.length) throw new Error('--in is required');
  return args;
}

function numberOrUndefined(value) {
  return Number.isFinite(value) ? Number(value) : undefined;
}

function sumKnown(fields, keys) {
  const included = {};
  let total = 0;
  for (const key of keys) {
    const value = numberOrUndefined(fields?.[key]);
    if (value === undefined) continue;
    included[key] = value;
    total += value;
  }
  return { totalMs: Number(total.toFixed(6)), included, missing: keys.filter((key) => !(key in included)) };
}

function ratio(a, b) {
  if (!Number.isFinite(a) || !Number.isFinite(b) || b === 0) return undefined;
  return Number((a / b).toFixed(6));
}

function timingMean(bucket, key) {
  const value = bucket?.[key]?.meanMs;
  return numberOrUndefined(value);
}

function normalizeArtifact(path, artifact) {
  if (artifact.schema === 'lc0_browser.tvmjs_vs_hybrid_matrix.v1') {
    const tvmjs = artifact.summary?.tvmjs ?? {};
    const hybrid = artifact.summary?.hybrid ?? {};
    const startupKnown = sumKnown(tvmjs.startupTimings, STARTUP_KEYS);
    return {
      sourceArtifact: path,
      sourceSchema: artifact.schema,
      ok: artifact.ok === true,
      kind: 'matrix',
      parameters: artifact.parameters,
      tvmjs: {
        batch: tvmjs.batch,
        fixtureCount: tvmjs.fixtureCount,
        invokeMs: numberOrUndefined(tvmjs.invokeMs),
        startupTimings: tvmjs.startupTimings,
        startupKnown,
        gpuBufferAllocation: tvmjs.gpuBufferAllocation,
        searchRows: numberOrUndefined(tvmjs.searchRows),
        searchMeanMs: numberOrUndefined(tvmjs.tvmSearchMeanMs),
        ortSearchMeanMs: numberOrUndefined(tvmjs.ortSearchMeanMs),
        searchToSingleInvokeRatio: ratio(tvmjs.tvmSearchMeanMs, tvmjs.invokeMs),
      },
      hybrid: {
        searchMeanMs: numberOrUndefined(hybrid.searchMeanElapsedMs),
        workerInitMs: numberOrUndefined(hybrid.workerInitMs),
        gpuBufferAllocation: hybrid.gpuBufferAllocation,
      },
      caveat: 'Matrix artifacts summarize search timings but may not include per-evaluation timing buckets unless generated by a newer smoke page.',
    };
  }
  if (artifact.schema === 'lc0_browser.tvmjs_webgpu_smoke.v1') {
    const result = artifact.result ?? {};
    const startupKnown = sumKnown(result.startupTimings, STARTUP_KEYS);
    const search = result.searchParity ?? {};
    const evalTiming = result.evalTiming ?? {};
    const evalPositionTiming = result.evalPositionTiming ?? {};
    const searchEvalTiming = search.tvmEvalTiming ?? {};
    const searchEvalPositionTiming = search.tvmEvalPositionTiming ?? {};
    return {
      sourceArtifact: path,
      sourceSchema: artifact.schema,
      ok: artifact.ok === true,
      kind: 'smoke',
      parameters: {
        batch: artifact.batch,
        fixtures: artifact.fixtures,
        fixtureCount: artifact.fixtureCount,
        searchVisits: artifact.searchVisits,
        searchFixtures: artifact.searchFixtures,
        searchRepeats: artifact.searchRepeats,
        ortCompare: artifact.ortCompare,
        ortEp: artifact.ortEp,
      },
      tvmjs: {
        batch: result.batch,
        fixtureCount: result.fixtureCount,
        invokeMs: numberOrUndefined(result.invokeMs),
        startupTimings: result.startupTimings,
        startupKnown,
        gpuBufferAllocation: result.gpuBufferAllocation,
        evalTiming,
        evalPositionTiming,
        searchRows: numberOrUndefined(search.searchRows ?? search.fixtureCount),
        searchVisits: numberOrUndefined(search.visits),
        searchMeanMs: numberOrUndefined(search.tvmTiming?.meanMs),
        ortSearchMeanMs: numberOrUndefined(search.ortTiming?.meanMs),
        searchToSingleInvokeRatio: ratio(search.tvmTiming?.meanMs, result.invokeMs),
        searchEvalTimingRows: numberOrUndefined(search.tvmEvalTimingRows ?? search.tvmEvalCalls),
        searchEvalTiming,
        searchEvalPositionTimingRows: numberOrUndefined(search.tvmEvalPositionTimingRows),
        searchEvalPositionTiming,
        meanEvalPhaseMs: Object.fromEntries(EVAL_KEYS.map((key) => [key, timingMean(evalTiming, key)]).filter(([, value]) => value !== undefined)),
        meanEvalPositionPhaseMs: Object.fromEntries(POSITION_EVAL_KEYS.map((key) => [key, timingMean(evalPositionTiming, key)]).filter(([, value]) => value !== undefined)),
        meanSearchEvalPhaseMs: Object.fromEntries(EVAL_KEYS.map((key) => [key, timingMean(searchEvalTiming, key)]).filter(([, value]) => value !== undefined)),
        meanSearchEvalPositionPhaseMs: Object.fromEntries(POSITION_EVAL_KEYS.map((key) => [key, timingMean(searchEvalPositionTiming, key)]).filter(([, value]) => value !== undefined)),
      },
      caveat: 'Search overhead cannot be inferred exactly without engine-level cache hit/miss and batch-fill counters; use per-eval buckets as profiling evidence, not as a promotion gate.',
    };
  }
  throw new Error(`${path}: unsupported artifact schema ${artifact.schema ?? '<missing>'}`);
}

function aggregate(records) {
  const searchMeans = records.map((record) => record.tvmjs.searchMeanMs).filter(Number.isFinite);
  const invokeMeans = records.map((record) => record.tvmjs.invokeMs).filter(Number.isFinite);
  const startupTotals = records.map((record) => record.tvmjs.startupKnown?.totalMs).filter(Number.isFinite);
  return {
    artifactCount: records.length,
    okArtifacts: records.filter((record) => record.ok).length,
    searchMeanMs: searchMeans.length ? {
      min: Math.min(...searchMeans),
      mean: searchMeans.reduce((a, b) => a + b, 0) / searchMeans.length,
      max: Math.max(...searchMeans),
    } : undefined,
    invokeMs: invokeMeans.length ? {
      min: Math.min(...invokeMeans),
      mean: invokeMeans.reduce((a, b) => a + b, 0) / invokeMeans.length,
      max: Math.max(...invokeMeans),
    } : undefined,
    startupKnownMs: startupTotals.length ? {
      min: Math.min(...startupTotals),
      mean: startupTotals.reduce((a, b) => a + b, 0) / startupTotals.length,
      max: Math.max(...startupTotals),
    } : undefined,
  };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) return usage();
  const records = [];
  for (const input of args.inputs) records.push(normalizeArtifact(input, JSON.parse(await readFile(input, 'utf8'))));
  const out = {
    schema: 'lc0_browser.tvmjs_timing_breakdown_summary.v1',
    generatedAt: new Date().toISOString(),
    ok: records.every((record) => record.ok),
    researchOnly: true,
    noStableRuntimePromotion: true,
    caveats: [
      'Startup total is a sum of known observed phases, not proof of a serialized critical path.',
      'GPU buffer allocation fields are createBuffer request telemetry only, not live GPU residency.',
      'Search loop overhead needs cache-hit/miss and batch-fill counters before kernel tuning decisions are final.',
    ],
    aggregate: aggregate(records),
    records,
  };
  if (args.write) {
    await mkdir(dirname(args.out), { recursive: true });
    await writeFile(args.out, `${JSON.stringify(out, null, 2)}\n`);
  }
  console.log(JSON.stringify(out, null, 2));
  if (!out.ok) process.exitCode = 1;
}

main().catch((error) => {
  console.error(error?.stack || error?.message || String(error));
  process.exit(1);
});
